import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { handle, hash, validateEntry } from '../worker/src/index.js';
function setup(){
  const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync(new URL('../worker/migrations/0001_initial.sql',import.meta.url),'utf8'));
  const DB={prepare(sql){return {bind(...args){this.args=args;return this;},async first(){return sqlite.prepare(sql).get(...this.args||[])||null;},async all(){return {results:sqlite.prepare(sql).all(...this.args||[])};},async run(){return sqlite.prepare(sql).run(...this.args||[]);}};},async batch(list){return Promise.all(list.map(s=>s.run()));}};
  const env={DB,PUBLIC_SITE_URL:'https://worldline22.github.io',OWNER_GITHUB_ID:'112759137',GITHUB_CLIENT_ID:'test-app',GITHUB_CLIENT_SECRET:'test-secret',ASSETS:{fetch:async()=>new Response('<html>Private editor</html>')}};
  return {env,sqlite};
}
const origin='https://workspace.example';
const request=(path,options={})=>new Request(origin+path,options);
const item=(visibility='private',kind='project')=>({title:'Research',body:'Sensitive research text',visibility,kind,summary:'Summary'});
async function session(env,expired=false){const token='a'.repeat(64);await env.DB.prepare('INSERT INTO sessions VALUES(?,?)').bind(await hash(token),Math.floor(Date.now()/1000)+(expired?-10:3600)).run();return {'Cookie':`__Host-yq_session=${token}`,'Origin':origin,'Content-Type':'application/json'};}
test('unauthenticated visitors cannot list, write, or load the workspace',async()=>{const {env}=setup();for(const path of ['/api/admin/items','/api/admin/items/secret']){assert.equal((await handle(request(path),env)).status,401);assert.equal((await handle(request(path,{method:'PUT',body:JSON.stringify(item())}),env)).status,401);}const r=await handle(request('/studio'),env);assert.equal(r.status,302);assert.equal(r.headers.get('location'),'/auth/login');assert.equal((await handle(request('/studio.html'),env)).status,404);});
test('private and archived content are excluded at the database query, including papers',async()=>{const {env}=setup(),headers=await session(env);for(const [id,visibility,kind,archived]of [['private','private','project',0],['public','public','project',0],['archived','public','note',1],['paper','public','paper',0]]){assert.equal((await handle(request('/api/admin/items/'+id,{method:'PUT',headers,body:JSON.stringify({...item(visibility,kind),archived})}),env)).status,200);}const response=await handle(request('/api/public/content'),env);const data=await response.json();assert.deepEqual(data.projects.map(x=>x.id),['public']);assert.deepEqual(data.papers.map(x=>x.id),['paper']);assert.deepEqual(data.notes,[]);assert.equal(response.headers.get('Cache-Control'),'no-store');assert.equal(response.headers.get('Access-Control-Allow-Origin'),'https://worldline22.github.io');assert.equal((await (await handle(request('/api/admin/items',{headers}),env)).json()).items.length,4);});
test('changing an entry to private removes it from public reads immediately',async()=>{const {env}=setup(),headers=await session(env);for(const visibility of ['public','private']){await handle(request('/api/admin/items/work',{method:'PUT',headers,body:JSON.stringify(item(visibility))}),env);const data=await (await handle(request('/api/public/content'),env)).json();assert.equal(data.projects.length,visibility==='public'?1:0);}});
test('expired sessions and cross-origin writes fail closed',async()=>{let {env}=setup();let headers=await session(env,true);assert.equal((await handle(request('/api/admin/items',{headers}),env)).status,401);({env}=setup());headers=await session(env);for(const badOrigin of ['https://attacker.example','null',''])assert.equal((await handle(request('/api/admin/items/work',{method:'PUT',headers:{...headers,Origin:badOrigin},body:JSON.stringify(item())}),env)).status,403);});
test('valid logout invalidates the session server-side',async()=>{const {env}=setup(),headers=await session(env);const r=await handle(request('/auth/logout',{method:'POST',headers}),env);assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/Max-Age=0/);assert.equal((await handle(request('/api/admin/items',{headers}),env)).status,401);});
test('validation rejects invalid visibility, unsafe URLs, oversized bodies, and SQL-like IDs',async()=>{assert.throws(()=>validateEntry(item(),"x'; DROP TABLE entries;--"));assert.throws(()=>validateEntry({...item(),visibility:'unlisted'},'x'));assert.throws(()=>validateEntry({...item(),url:'javascript:alert(1)'},'x'));assert.throws(()=>validateEntry({...item(),body:'x'.repeat(60001)},'x'));const {env}=setup(),headers=await session(env);const r=await handle(request('/api/admin/items/x',{method:'PUT',headers,body:'x'.repeat(100001)}),env);assert.equal(r.status,413);});
test('OAuth requires matching browser state and single-use PKCE before issuing owner-only sessions',async()=>{const {env}=setup();const login=await handle(request('/auth/login'),env);const auth=new URL(login.headers.get('location'));assert.equal(auth.searchParams.get('code_challenge_method'),'S256');assert.equal(auth.searchParams.has('scope'),false);const state=auth.searchParams.get('state');let exchanges=0;const fake=async(url,options)=>{exchanges++;if(url.endsWith('access_token')){assert.equal(JSON.parse(options.body).code_verifier.length,64);return Response.json({access_token:'short-lived-test-token'});}return Response.json({id:112759137});};const callback='/auth/callback?state='+state+'&code=example';assert.equal((await handle(request(callback),env,fake)).status,400);const owner=await handle(request(callback,{headers:{Cookie:`__Host-yq_oauth=${state}`}}),env,fake);assert.equal(owner.status,302);assert.equal(owner.headers.get('location'),'/studio');assert.match(owner.headers.get('set-cookie'),/HttpOnly/);assert.match(owner.headers.get('set-cookie'),/Secure/);assert.equal(exchanges,2);assert.equal((await handle(request(callback,{headers:{Cookie:`__Host-yq_oauth=${state}`}}),env,fake)).status,400);});
test('a different GitHub account never receives a session',async()=>{const {env}=setup();const r=await handle(request('/auth/login'),env);const state=new URL(r.headers.get('location')).searchParams.get('state');const fake=async u=>Response.json(u.endsWith('access_token')?{access_token:'test'}:{id:999});const denied=await handle(request('/auth/callback?state='+state+'&code=example',{headers:{Cookie:`__Host-yq_oauth=${state}`}}),env,fake);assert.equal(denied.status,403);assert.equal((await env.DB.prepare('SELECT COUNT(*) AS n FROM sessions').first()).n,0);});
test('the protected editor has CSP and cannot be cached',async()=>{const {env}=setup(),headers=await session(env);const r=await handle(request('/studio',{headers}),env);assert.equal(r.status,200);assert.match(r.headers.get('Content-Security-Policy'),/frame-ancestors 'none'/);assert.equal(r.headers.get('Cache-Control'),'no-store');});
