// Editorial source for the public Library. Examples are deliberately small,
// invented teaching models; evidence fields describe the supplied PDFs only.
import { morePapers } from './library-more-papers.mjs';
export const papers = [
  {
    id:'vtc', name:'VTC', venue:'OSDI 2026', category:'movement', topic:'Avoid copies', time:5,
    title:'VTC: DNN Compilation with Virtual Tensors for Data Movement Elimination',
    authors:'Muyan Hu, Ahan Gupta, Jiachen Yuan, Vima Gupta, Taeksang Kim, Xin Xu, Janardhan Kulkarni, Ofer Dekel, Vikram Adve, and Charith Mendis',
    file:'osdi26-hu-muyan.pdf', headline:'Change the address.\nSkip the copy.',
    sourceUrl:'https://www.usenix.org/conference/osdi26/presentation/hu-muyan', sourceLabel:'USENIX',
    pdfUrl:'https://www.usenix.org/system/files/osdi26-hu-muyan.pdf',
    takeaway:'VTC replaces some intermediate arrays with address mappings, so kernels can read existing data or write straight to its destination.',
    hook:'What if an array could exist without another copy of its numbers?',
    analogy:'Think of a library catalog: it tells you where a book lives. You do not need to photocopy the book onto a new shelf.',
    problem:'A tensor is an array of numbers. Splitting or rearranging it can create temporary arrays, even though the numbers themselves do not change.',
    before:[['Calculate','Produce new token data'],['Temporary array','Write numbers to GPU memory','costly'],['Split + copy','Read and write them again','costly'],['Token cache','The final destination']],
    after:[['Calculate','Same mathematical work'],['Address map','Choose each number’s destination','hot'],['Token cache','Write directly into the right slots']],
    beforeCaption:'The intermediate array exists only to move values onward.',
    afterCaption:'The virtual tensor describes storage; it does not allocate another full array.',
    demoTitle:'Split an array without copying it',
    demoIntro:'Read the last three elements of A. Switch between a physical copy and a virtual view: the answer stays [40, 50, 60].',
    methods:[['Describe the mapping','Record which original tensor and index hold each value.'],['Rewrite kernel I/O','Adjust reads and writes around the calculation, including between separate kernels.'],['Keep profitable choices','Profile alternatives and resolve conflicting transformations. An awkward access pattern can erase the savings.']],
    contribution:'A general virtual-tensor representation plus a search for profitable data-movement elimination. Efficient contiguous chunks can be enough; the whole tensor need not be contiguous.',
    bridge:['Tensor access rules','Address mappings','Fewer intermediate copies'],
    connection:'Consider expressing split, reshape, and cache-update patterns as address rules in Torch-Helion, with legality conditions that preserve the original reads and writes.',
    experiment:'Compare a materialized intermediate with direct destination writes. Check numerical equality, bytes moved, peak memory, and measured kernel latency.',
    caution:'Removing a copy does not automatically improve runtime. Verify memory access efficiency and the replacement compute kernel.',
    evidence:[['1.28×','Average reported speedup','Against the best of four compiler baselines for each tested case on NVIDIA A100 and H100. Maximum: 1.93×.'],['17.5%','Average peak-memory savings','Against PyTorch on A100 at batch sizes 1 and 16. Maximum: 60%.']],
    limitation:'The main suite uses selected layers or blocks from five model families. Against specialized vLLM, the tested Llama decoder layer improves only 1.011× on A100, with no improvement on H100.',
    evidencePage:12, evidenceSections:'§§7.1–7.5; Tables 1–3; Figure 9',
    sourceSections:[['§§3–4 · Virtual tensors and the cache example',6],['§§5–6 · Search and implementation',8],['§7 · Evaluation and baseline details',11]],
    related:'tensor-seeks-layout', relatedReason:'Layout choices can make a seemingly useful copy-removal rule expensive.'
  },
  {
    id:'fuseflow',name:'FuseFlow',venue:'ASPLOS 2026',category:'fusion',topic:'Connect sparse work',time:6,
    title:'FuseFlow: A Fusion-Centric Compilation Framework for Sparse Deep Learning on Streaming Dataflow',
    authors:'Rubens Lacouture, Nathan Zhang, Ritvik Sharma, Marco Siracusa, Fredrik Kjolstad, Kunle Olukotun, and Olivia Hsu',
    file:'asplos2026fuseflow.pdf',headline:'Pass the value.\nKeep its position.',
    sourceUrl:'https://arxiv.org/abs/2511.04768', sourceLabel:'arXiv',
    pdfUrl:'https://arxiv.org/pdf/2511.04768v2',
    takeaway:'FuseFlow joins sparse operations into streaming pipelines, coordinating both the values and the coordinates that say where they belong.',
    hook:'Skipping zeros is easy to picture. Connecting the remaining values is the hard part.',
    analogy:'Imagine two conveyor belts carrying numbered packages. A worker must match the package numbers before combining their contents.',
    problem:'A sparse tensor has many zeros. Storing only nonzero values saves work, but the compiler must also track their positions and visit them in a compatible order.',
    before:[['Sparse operation A','Track coordinates + values'],['Write intermediate','Store values and their positions','costly'],['Read intermediate','Reconstruct the next traversal','costly'],['Sparse operation B','Resume computation']],
    after:[['Scan + match','Find compatible coordinates','hot'],['Calculate + reduce','Produce completed partial results'],['Stream into next operation','Pass positions together with values','hot']],
    beforeCaption:'Separate expressions repeatedly materialize their intermediate results.',
    afterCaption:'A connected dataflow graph passes results onward as dependencies allow.',
    demoTitle:'A sparse dot product, one match at a time',
    demoIntro:'A = [2, 0, 3, 0] and B = [0, 4, 5, 0]. Only position 2 is nonzero in both. Multiply matching positions, then add the products.',
    methods:[['Express legal orders','Fused expressions and a partial-order graph retain sparse-format and dependency constraints.'],['Build fusion tables','A planning representation connects coordinate streams, value streams, and computation.'],['Generate the pipeline','Scanners, matchers, arithmetic, and reducers form the streaming program. Factored iteration avoids excess bookkeeping.']],
    contribution:'Cross-expression sparse fusion, enabled by fused expressions with ordering constraints and a fusion-table intermediate representation. This goes beyond combining a single sparse expression.',
    bridge:['Fusion legality','Coordinate + value order','Streaming dataflow plan'],
    connection:'For a sparse or dataflow backend, Torch-Helion would need explicit traversal and dependency constraints when connecting operations. A matching shape alone is insufficient.',
    experiment:'Try no fusion, partial fusion, and full fusion for a small gather → transform → activation workload. Count intermediate traffic and repeated arithmetic separately.',
    caution:'Full fusion may repeat work and run slower. The scheduling interface lets users select fusion regions; full automatic schedule selection is future work.',
    evidence:[['≈2.7×','GPT-3 Small with BigBird','Reported speedup over the unfused baseline in the cycle-accurate dataflow simulator.'],['Simulation','Primary evidence','Selected small kernels are checked against post-synthesis FPGA RTL simulation; this is not a full model on fabricated hardware.']],
    limitation:'These are sparse streaming-accelerator experiments. Treat the fusion constraints as transferable ideas, not as measured GPU or Torch-Helion speedups.',
    evidencePage:11,evidenceSections:'§§8.1–8.3; Figures 12–13',
    sourceSections:[['§§3–4 · Motivation and compilation flow',4],['§§5–6 · Ordering constraints and fusion tables',7],['§8 · Simulator and hardware validation',10]],
    related:'fast-and-fusiest',relatedReason:'Once fusion choices are legal, the next problem is searching them efficiently.'
  },
  {
    id:'graphturbo',name:'GraphTurbo',venue:'OSDI 2023',category:'fusion',topic:'Fit the fast memory',time:5,
    title:'Effectively Scheduling Computational Graphs of Deep Neural Networks toward Their Domain-Specific Accelerators',
    authors:'Jie Zhao, Siyuan Feng, Xiaoqiang Dan, Fei Liu, Chengke Wang, Sheng Yuan, Wenyuan Lv, and Qikai Xie',
    file:'osdi23-zhao.pdf',headline:'Let memory\nset the schedule.',
    sourceUrl:'https://www.usenix.org/conference/osdi23/presentation/zhao', sourceLabel:'USENIX',
    pdfUrl:'https://www.usenix.org/system/files/osdi23-zhao.pdf',
    takeaway:'GraphTurbo groups and schedules operations around the accelerator’s memory hierarchy, adapting to different memory demands across network stages.',
    hook:'If later layers need less room, why give them the same schedule?',
    analogy:'A small kitchen counter fits one large tray or two small trays. A good cook changes the work schedule as the trays get smaller.',
    problem:'Small independent kernels can repeatedly exchange results through slower memory. A fixed piece size also leaves room unused when later stages produce smaller tensors.',
    before:[['Layer A kernel','Compute one small group'],['Off-core memory','Save and reload intermediate data','costly'],['Layer B kernel','Another small group'],['Fixed schedule','Ignore changing memory demand']],
    after:[['Hardware-aware group','Combine compatible layers','hot'],['Tile to fit','Choose pieces for available memory'],['Schedule across layers','Reuse buffers and overlap eligible work','hot']],
    beforeCaption:'Grouping the graph before considering hardware can miss reuse and parallelism.',
    afterCaption:'Grouping, tiling, ordering, and kernel generation cooperate.',
    demoTitle:'How many image tiles fit on the counter?',
    demoIntro:'The toy fast memory has 8 slots. One early-stage image tile takes 6; one later-stage tile takes 3. Change the stage and number of tiles.',
    methods:[['Group the graph','Use hardware information to construct coarse subgraphs spanning layers or blocks.'],['Choose tiles + order','Split subgraphs into pieces and exploit uneven memory needs across network stages.'],['Generate joint kernels','Reuse local buffers and schedule across layers to overlap eligible transfers and calculations.']],
    contribution:'Hardware-aware graph partitioning connected to memory-sensitive scheduling and cross-layer kernel generation. Different stages can use different execution granularities.',
    bridge:['Architecture memory limits','Fusion + tile decisions','Cross-layer schedule'],
    connection:'Make memory capacity and hierarchy explicit inputs to Torch-Helion’s planner. Let fusion groups and tile sizes change when the architecture profile changes.',
    experiment:'Run the same two-stage graph under two local-memory budgets. Check that selected groups and tiles change, then measure traffic and latency.',
    caution:'The illustration counts only working tiles. A real capacity check must also include weights, outputs, alignment, and double buffering.',
    evidence:[['11.15×','Average throughput vs. TVM','Reported on the STCP920 specialized accelerator. The gain over a reproduced AStitch implementation is 6.16×.'],['1.06×','Narrower GPU case study','Reported on A100 against CUTLASS with convolution fusion. This comparison has a different scope from the main accelerator suite.']],
    limitation:'The large headline gains are specific to the specialized accelerator evaluation. The implementation does not support dynamically shaped tensors.',
    evidencePage:11,evidenceSections:'§5 · Evaluation; §5.6 · GPU case study',
    sourceSections:[['§2 · Why memory demand changes across layers',4],['§§3–4 · Graph transformation and kernel generation',6],['§5 · Accelerator results and GPU case study',11]],
    related:'t10',relatedReason:'T10 asks what changes when fast memory is split among many connected cores.'
  },
  {
    id:'tensor-seeks-layout',name:'Tensor Seeks Layout',venue:'Preprint · August 2026',category:'planning',topic:'Choose layouts globally',time:6,
    title:'Tensor Seeks Layout: Formalizing Layout Selection for ML Compilers',
    authors:'Clemens Eisenhofer, Yuwen Jia, Daniel Kroening, and Sergey Pupyrev',
    file:'Tensor_Seeks_Layout.pdf',headline:'The best parts\ncan make a slow whole.',
    sourceUrl:'https://arxiv.org/abs/2608.21555', sourceLabel:'arXiv',
    pdfUrl:'https://arxiv.org/pdf/2608.21555v1',
    takeaway:'Tensor Seeks Layout formalizes global layout selection and gives exact solution methods under a stated cost model, including the cost of conversions.',
    hook:'Two fast operators can become a slow program if they disagree about layout.',
    analogy:'Two students like their notes sorted differently. Each reads quickly, but repeatedly re-sorting the shared notebook can take longer than reading it.',
    problem:'A layout says where tensor elements live. One operator may prefer rows together, another columns together. Converting between them costs time.',
    before:[['Operator A · row layout','1 time unit'],['Convert rows → columns','5 time units','costly'],['Operator B · column layout','1 time unit']],
    after:[['Operator A · column layout','2 time units','hot'],['No conversion','Same layout on the connecting edge'],['Operator B · column layout','1 time unit']],
    beforeCaption:'Each operator gets its favorite layout. <strong>Total: 7 units.</strong> Toy costs.',
    afterCaption:'A slightly slower A improves the whole sequence. <strong>Total: 3 units.</strong> Toy costs.',
    demoTitle:'When is conversion worth paying for?',
    demoIntro:'Plan A uses each operator’s favorite layout (1 + conversion + 1). Plan B keeps one common layout (2 + 1). Move the conversion-cost slider.',
    methods:[['Define the objective','Add operator costs and required per-tensor conversion costs. A converted tensor shared by consumers is charged once.'],['Prove the difficulty','The general problem is hard. Bounded-treewidth graphs admit an exact polynomial-time algorithm.'],['Solve general instances','Encode legal choices and weighted penalties for a MaxSAT solver, which optimizes the stated objective.']],
    contribution:'A formal optimization problem, complexity results, and exact algorithms. It separates a failure of search from a failure of the cost model.',
    bridge:['Operator + conversion costs','Global layout assignment','Measured validation'],
    connection:'Include layout conversion costs in Torch-Helion’s global objective. When a predicted winner is slow, investigate the cost estimate as well as the search.',
    experiment:'For a tiny branched graph, enumerate layout assignments and charge shared conversions once. Compare the planner’s chosen cost with both the exact minimum and measured runtime.',
    caution:'“Optimal” means best under the formula and allowed choices. Later tiling and data movement can invalidate an early estimate.',
    evidence:[['Exact','Optimal under the model','The solver finishes within seconds on most tested instances. Exact search does not make the hardware cost model exact.'],['63.9 vs. 20.9','Million cycles on ResNet-50','The solver-based assignment is slower than the production rule-based assignment on AWS Trainium; lower is better.']],
    limitation:'Simple heuristics can cause roughly 5× slowdowns, but an exact solver can also lose in real execution when costs are inaccurate. The ResNet-50 comparison exposes that distinction.',
    evidencePage:16,evidenceSections:'§5 · Evaluation; Table 1; discussion of cost-model fidelity',
    sourceSections:[['§2 · Layout selection and conversion sharing',3],['§§3–4 · Complexity and exact algorithms',6],['§5 · Cost-model error and measured execution',14]],
    related:'fast-and-fusiest',relatedReason:'Both papers reason about optimal plans under a model, but optimize different choices.'
  },
  {
    id:'fast-and-fusiest',name:'Fast and Fusiest',venue:'MICRO 2026 · supplied manuscript',category:'planning',topic:'Prune the search',time:6,
    title:'Fast and Fusiest: An Optimal Fusion-Aware Mapper for Accelerator Design',
    authors:'Tanner Andrulis, Michael Gilbert, Vivienne Sze, and Joel S. Emer',
    file:'Fast_and_Fusiest.pdf',headline:'Keep the trade-offs.\nDiscard the dead ends.',
    sourceUrl:'https://arxiv.org/abs/2602.15166', sourceLabel:'arXiv',
    pdfUrl:'https://arxiv.org/pdf/2602.15166v2',
    takeaway:'The Fast and Fusiest Mapper discards partial execution plans that cannot improve the final modeled result, then combines compatible survivors.',
    hook:'How do you explore a huge number of fusion plans without trying every combination?',
    analogy:'Think of jigsaw pieces with the same connecting edges. If one costs more in every relevant way, you can discard it before assembling the whole puzzle.',
    problem:'Every operator has many tile, storage, and execution-order choices. Fusion links neighboring choices together, so the number of complete plans grows rapidly.',
    before:[['Many choices per operator','Tiles × order × storage'],['Combine every choice','The number of plans explodes','costly'],['Evaluate full programs','Most work is spent on inferior plans']],
    after:[['Summarize partial plans','Keep interfaces + costs + memory lifetimes','hot'],['Prune dominated alternatives','Compare within compatible groups'],['Join surviving plans','Repeat until the workload is covered','hot']],
    beforeCaption:'A locally fastest plan can still be a bad neighbor, or use too much memory.',
    afterCaption:'Preserve useful trade-offs and the information needed for later joins.',
    demoTitle:'Which plans are safe to discard?',
    demoIntro:'These three toy plans have the same boundary interface, equal energy, and the same memory-lifetime pattern. Lower time and lower memory are better.',
    methods:[['Keep boundary information','Track shared tile shapes, storage locations, and exchange order to recognize compatible partial mappings.'],['Keep the Pareto frontier','Remove a plan only when another compatible plan is no worse in all relevant costs and resource requirements.'],['Join + prune again','Compose survivors and retain memory-reservation information, so pruning preserves the supported optimum.']],
    contribution:'Identifying the sufficient interface and resource information that makes early pruning safe. Memory lifetimes matter, not just a single peak-memory number.',
    bridge:['Compatible partial schedules','Safe dominance pruning','Smaller fusion search'],
    connection:'Torch-Helion could retain several useful plans per boundary interface instead of only the locally fastest one. Pruning must account for resources and their lifetimes.',
    experiment:'On a tiny supported graph, compare pruned search with exhaustive enumeration. Require the same best modeled result before trying larger graphs.',
    caution:'The table below simplifies the paper’s pruning conditions. Real plans also need energy, compatibility, and reservation information to justify safe removal.',
    evidence:[['≈1.5','CPU-hours to find the optimum','One transformer mapping experiment. Reconstructed baseline searches remain short of optimality at 10,000× this search-time budget; baseline times use cached evaluations.'],['Up to 1.8×','Reduction in energy × delay','A separate modeled accelerator comparison against TransFusion. This is a performance/energy objective, not a search-time ratio.']],
    limitation:'The 10,000× comparison is about finding a mapping, not running a neural network. Optimality is limited to the supported search space and hardware model.',
    evidencePage:9,evidenceSections:'§7.2 · Baseline methodology; §7.4 and Figure 8; §8 · Accelerator design',
    sourceSections:[['§§3–4 · Partial mappings and constrained optimization',3],['§§5–6 · Reservation trees and mapper',5],['§§7–8 · Search time and accelerator evaluation',8]],
    related:'tensor-seeks-layout',relatedReason:'A perfect search still needs accurate costs to select a fast real program.'
  },
  {
    id:'t10',name:'T10',venue:'SOSP 2024',category:'movement',topic:'Coordinate connected cores',time:6,
    title:'Scaling Deep Learning Computation over the Inter-core Connected Intelligence Processor with T10',
    authors:'Yiqi Liu, Yuqi Xue, Yu Cheng, Lingxiao Ma, Ziming Miao, Jilong Xue, and Jian Huang',
    file:'t10-sosp24.pdf',headline:'Compute locally.\nExchange deliberately.',
    sourceUrl:'https://arxiv.org/abs/2408.04808', sourceLabel:'arXiv',
    pdfUrl:'https://arxiv.org/pdf/2408.04808v2',
    takeaway:'T10 coordinates tensor placement, computation, and exchanges across connected cores, balancing private-memory use against communication overhead.',
    hook:'What if two cores could share a large matrix by taking turns with its pieces?',
    analogy:'Two students each hold half of a reference book. They do the exercises for their half, exchange halves, and finish without owning two complete books.',
    problem:'On an IPU, each core has a small private memory and fast links to other cores. Extra copies waste capacity; unplanned exchanges waste bandwidth.',
    before:[['Core 0 · full weights','Store W₀ and W₁'],['Core 1 · full weights','Store W₀ and W₁ too','costly'],['Compute independently','More storage, fewer exchanges']],
    after:[['Split the weights','Core 0 owns W₀; core 1 owns W₁','hot'],['Compute → exchange','Each core uses its piece, then swaps'],['Compute again','Finish the remaining output columns','hot']],
    beforeCaption:'Replicating a complete weight matrix on both cores uses four half-matrix blocks.',
    afterCaption:'Two blocks suffice in this toy arrangement, at the cost of exchanging the halves.',
    demoTitle:'Walk through a two-core matrix multiply',
    demoIntro:'Each core owns a different input row. Weight piece W₀ makes output column 0; W₁ makes column 1. Step through the computation and exchange.',
    methods:[['Describe an rTensor','Record how a tensor is split across cores and time, and how its pieces rotate.'],['Search compute–shift plans','Balance local computation and predictable exchanges using measured compute and transfer costs.'],['Budget the whole model','Choose compact idle arrangements and efficient active arrangements, accounting for the cost of switching.']],
    contribution:'A rotating-tensor abstraction for compute–shift execution, plus a global trade-off between each operation’s idle footprint, active footprint, and setup cost.',
    bridge:['Distributed tensor layout','Compute + exchange schedule','Whole-model memory budget'],
    connection:'For a backend with private core memories, Torch-Helion’s schedule needs explicit placement and transfer steps. Communication and setup costs belong in the objective.',
    experiment:'Compare replicated and rotating weights for a small matrix multiply. Measure total memory, bytes exchanged, setup time, and execution time separately.',
    caution:'This is an architecture-specific idea: a GPU memory hierarchy and an IPU’s private core memories require different execution plans.',
    evidence:[['1.69×','Average speedup over Roller','Reported on real Graphcore IPU MK2 hardware. Maximum improvement: 3.3×.'],['Larger batches','Improved capacity','T10 runs larger tested batches that other baselines cannot fit in the chip’s distributed on-chip memory.']],
    limitation:'The large-LLM comparisons run selected layers because a full LLM does not fit on the tested IPU. A separate experiment adding external high-bandwidth memory emulates that memory.',
    evidencePage:10,evidenceSections:'§5.2 and Figure 12; §5.7 · LLM scope; §6 · Emulated HBM',
    sourceSections:[['§3 · Two-core compute–shift example',3],['§4 · rTensor and idle/active plans',4],['§§5–6 · Hardware results and limits',9]],
    related:'graphturbo',relatedReason:'Both make memory capacity part of scheduling, at different levels of the architecture.'
  },
  ...morePapers
];
